spring:
  profiles:
    active: default
    
server:
  port: 8101    

---
spring:
  profiles: default
  
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver