spring:
  profiles:
    active: default
    
server:
  port: 8101    

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8200}/eureka/
    fetch-registry: true
    register-with-eureka: true  
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
---
spring:
  profiles: default
  
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver